### PR TITLE
Update for Python 3

### LINKED ISSUE #3: Update for python 3

### PR DESCRIPTION
**Pull request by quantumjot**
Automated conversion using 2to3.

Closes #3.

### CODE REVIEW

**Comment by mnaqvi-code** [comment]
Hi 
I am using the heteropolymer model and using the following fitting command:
ising.fit_heteropolymer(curves[0:12], topology1[0:12], popsize=10, maxiter= 10000)
I am getting the following error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-26-f3869b64ba1e> in <module>
----> 1 ising.fit_heteropolymer(curves[0:12], topology1[0:12], popsize=10, maxiter= 10000)

~\anaconda3\lib\site-packages\pyfolding\ising.py in fit_heteropolymer(equilibrium_curves, topologies, popsize, tol, maxiter, **kwargs)
    755     for protein, topology in zip(equilibrium_curves, topologies):
    756         fit_func.append(protein, topology)
--> 757         print( '+ added {0:s} with topology {1:s}'.format(protein.ID, [d().name for d in topology]))
    758 
    759     # do the fitting

TypeError: unsupported format string passed to list.__format__

Please inform me if you know how to fix it. It seems this is an issue with python 3 version? Thanks

**Comment by quantumjot** [comment]
Thanks @mnaqvi-code. I've opened an issue here: #5

**Comment by quantumjot** [comment]
@mnaqvi-code - please try again now, hopefully this has been fixed.

**Comment by mnaqvi-code** [comment]
Hi Alan
                 Thanks a lot for fixing the issues. It is now working fine.

Best Regards

Mohsin M. Naqvi.

**Pull request merged**
